import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Diátaxis Framework Structure
  tutorialsSidebar: [
    {
      type: 'category',
      label: '📖 Learning Path',
      items: [{type: 'autogenerated', dirName: 'tutorials'}],
    },
  ],
  
  guidesSidebar: [
    {
      type: 'category', 
      label: '🛠️ How-to Guides',
      items: [{type: 'autogenerated', dirName: 'guides'}],
    },
  ],
  
  referenceSidebar: [
    {
      type: 'category',
      label: '📚 Technical Reference', 
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
  ],
  
  explanationSidebar: [
    {
      type: 'category',
      label: '💡 Background & Context',
      items: [{type: 'autogenerated', dirName: 'explanation'}],
    },
  ],
};

export default sidebars;
