name: Documentation CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
    paths: 
      - 'docs-site/**'
      - '.github/workflows/docs-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs-site/**'

jobs:
  quality-checks:
    name: Quality Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs-site
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: docs-site/package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build documentation
      run: npm run build
    
    - name: Check for broken links
      run: |
        npm install -g broken-link-checker
        blc http://localhost:3000 --recursive --ordered --exclude-external || true
    
    - name: Lint markdown files
      run: |
        npm install -g markdownlint-cli
        markdownlint docs/**/*.md --ignore node_modules
    
    - name: Check spelling
      run: |
        npm install -g cspell
        cspell "docs/**/*.md" --config .cspell.json || true

  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    needs: quality-checks
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: ./docs-site
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: docs-site/package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build for production
      run: npm run build
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs-site/build
        destination_dir: docs-site